### ISSUE TITLE
coverage XML + Gitlab coverage report

### ISSUE THREAD

**Issue by m1kc** [m1kc/django-spinproject#19]
pytest.ini

    addopts = --cov=. --cov-config=.coveragerc --cov-report term --cov-report html --cov-report xml

.gitlab-ci.yml

```yml
...
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    reports:
      cobertura: coverage.xml
```
