### ISSUE TITLE
CI: exclude poetry virtualenvs from cache

### ISSUE THREAD

**Issue by m1kc** [m1kc/django-spinproject#25]
Sometimes packages removed from both pyproject.toml and poetry.lock still can be found in a cached virtualenv. This leads to a lot of head-scratching in certain scenarios.

```yml
cache:
  paths:
    - .cache/pip
    - .cache/pypoetry/artifacts
    - .cache/pypoetry/cache
```
